<?php

namespace VT\UsersBundle\Repository;
use VT\VTCoreBundle\Entity\VTEntityRepository;

/**
 * DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorRepository extends VTEntityRepository
{
	/**
     * @param array $fullSpec
     * @param boolean $countOnly
     * @return array
     */
    public function fetchDoctorsByFilter($fullSpec, $countOnly = false)
    {

        $searchSpec = $fullSpec['searchSpec'];
        $sortSpec = $fullSpec['sortSpec'];
        $pageSpec = $fullSpec['pageSpec'];

        $extraQ = "";

        if(!empty($searchSpec)) {
            if (array_key_exists('keyword', $searchSpec)) {
                $k = $searchSpec['keyword'];
                if (!empty($k)) {
                    if (!empty($extraQ))
                        $extraQ .= " and ";
                    $extraQ .= "(d.name like '%" . $k . "%' )";
                }
            }
        }

        $cq = "";
        $cq .= "select count(distinct d.id) ";
        $cq .= "from UsersBundle:Doctor as d ";
        if (!empty($extraQ)) {
            $cq .= "where " . $extraQ;
        }

        $q = "";
        if (!$countOnly) {
            $q .= "select d ";
            $q .= "from UsersBundle:Doctor as d ";
            if (!empty($extraQ)) {
                $q .= "where " . $extraQ;
            }
        }

        // Total Count
        $tql = $this->createQuery($cq);
        $totalRecords = $tql->getResult();

        // doctors
        $doctors = array();
        if (!$countOnly) {
            $dql = $this->createQuery($q);
            if (!empty($pageSpec) && $pageSpec['pageSize'] != "") {
                $dql->setMaxResults($pageSpec['pageSize'])->setFirstResult(($pageSpec['currentPage'] - 1) * $pageSpec['pageSize']);
            }
            $doctors = $dql->getResult();
            return array("totalRecords" => $totalRecords, "doctors" => $doctors);
        } else {
            return array("totalRecords" => $totalRecords[0][1]);
        }
    }
}
