<?php

namespace VT\UsersBundle\Repository;

/**
 * TaxMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
