<?php

namespace VT\UsersBundle\Repository;

/**
 * UserVisitTestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVisitTestsRepository extends \Doctrine\ORM\EntityRepository
{
}
