<?php

namespace VT\LabsBundle\Repository;

/**
 * LabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabRepository extends \Doctrine\ORM\EntityRepository
{
}
