<?php

namespace VT\TestsBundle\Repository;

/**
 * DepartmentMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
