<?php

namespace VT\TestsBundle\Repository;
use Doctrine\ORM\Query;
use VT\VTCoreBundle\Entity\VTEntityRepository;

/**
 * TestMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestMasterRepository extends VTEntityRepository
{	
    public function fetchTestsByDeptId($deptId = null, $keyword = null)
    {
        $q = "";
        $q .= " select t.id, t.name ";
        $q .= " from TestsBundle:TestMaster as t ";
        if (!empty($deptId) and !empty($keyword)) {
            $q .= " where t.department = '" . $deptId . "' and t.name like '%" . $keyword . "%' ";
            $q .= " and t.deleted = 0 ";
        } else if (!empty($deptId)) {
            $q .= " where t.department = '" . $deptId . "' ";
            $q .= " and t.deleted = 0 ";
        } else if (!empty($keyword)) {
            $q .= " where t.name like '%" . $keyword . "%' ";
            $q .= " and t.deleted = 0 ";
        } else {
            $q .= " where t.deleted = 0 ";
        }
        
        $testList = $this->createQuery($q)->getResult(Query::HYDRATE_ARRAY);
        return $testList;
    }

    public function fetchCostByTestId($testId = null)
    {
        $q = "";
        $q .= " select t.defaultCost as cost";
        $q .= " from TestsBundle:TestMaster as t ";
        $q .= " where t.id = '" . $testId . "'";
        
        $testList = $this->createQuery($q)->getResult(Query::HYDRATE_ARRAY);
        return $testList;
    }
}
