<?php

namespace VT\PaymentBundle\Repository;

/**
 * PayuWalletAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayuWalletAuthRepository extends \Doctrine\ORM\EntityRepository
{
}
